# Generated by Django 4.2.5 on 2023-09-21 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "updated_by",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("company_id", models.UUIDField()),
            ],
            options={
                "verbose_name": "UserRole",
                "verbose_name_plural": "UserRoles",
                "db_table": "userrole",
            },
        ),
    ]
